import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Providers from "@/app/Providers";
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import HeaderController from "@/app/components/layout/HeaderController";
import ReduxProvider from "./ReduxProvider"
import {UserProvider} from "@/context/UserContext";
import ThemeToggle from "@/app/components/theme/ThemeToggle";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <UserProvider>
            <HeaderController/>
            <div className="fixed left-6 top-2 z-50">
                <ThemeToggle/>
            </div>
            <div className="">
                <ReduxProvider>
                    <Providers>{children}</Providers>
                </ReduxProvider>
            </div>
            <ToastContainer
                rtl={true}
                position="top-center"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                pauseOnHover
                draggable
                theme="colored"
            />
        </UserProvider>
        </body>
        </html>
    );
}
