import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Providers from "@/app/Providers";
import ThemeToggle from "@/app/components/theme/ThemeToggle";
import {ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import HumburgerMenu from "@/app/components/ui/HamburgerMenu";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <HumburgerMenu/>
        {/*<div className="fixed left-4 z-50">*/}
        {/*    <ThemeToggle />*/}
        {/*</div>*/}
        <div className="!pt-20">
            <Providers>{children}</Providers>
        </div>
        <ToastContainer
            rtl={true}                // راست چین برای فارسی
            position="top-center"     // موقعیت نمایش
            autoClose={3000}          // زمان خودکار بسته شدن (میلی‌ثانیه)
            hideProgressBar={false}   // نوار پیشرفت
            newestOnTop={false}       // جدیدترین پیام بالای لیست باشه؟
            closeOnClick               // بسته شدن با کلیک
            pauseOnHover
            draggable
            theme="colored"
        />
        </body>
        </html>
    );
}
